name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm ci
      - run: npm run all
      - name: Verifying no unstaged changes
        run: __test__/verify-no-unstaged-changes.sh
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: semver snapshot
        id: get_snapshot_version
        uses: ./
        with:
          version: v2.0.1-SNAPSHOT
      - name: semver snapshot test
        run: |
          echo "Version: ${{ steps.get_snapshot_version.outputs.version }}"
          echo "Build Version: ${{ steps.get_snapshot_version.outputs.build-version }}"
          echo "Next Version: ${{ steps.get_snapshot_version.outputs.next-version }}"
      - name: semver
        id: get_version
        uses: ./
        with:
          version: v2.0.1
      - name: semver test
        run: |
          echo "Version: ${{ steps.get_version.outputs.version }}"
          echo "Build Version: ${{ steps.get_version.outputs.build-version }}"
          echo "Next Version: ${{ steps.get_version.outputs.next-version }}"

# Test the action here
